[package]
name = "egui-font-rendering-bug"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.eframe]
git = "https://github.com/emilk/egui"
rev = "d3c002a4e5ee9f1aacf9e0ddd9c97e74dd4c95a3"
